# Changes here will be overwritten by Copier
_commit: 1.4.0
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2024'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: true
insiders_email: insiders@pawamoy.fr
insiders_repository_name: griffe-runtime-objects
project_description: Make runtime objects available through `extra`.
project_name: griffe-runtime-objects
public_release: false
python_package_command_line_name: ''
python_package_distribution_name: griffe-runtime-objects
python_package_import_name: griffe_runtime_objects
repository_name: griffe-runtime-objects
repository_namespace: mkdocstrings
repository_provider: github.com

